import Head from 'next/head'
import Image from 'next/future/image'
import React, { useEffect, useState } from "react"
const parse = require('html-react-parser');
import LogoBanner from "./common/logo-banner";
import styles from '../styles/Home.module.css';
let dispc = false;
function showPage(){
  dispc = true;
}
export default function Home({ Component, pageProps }) {
  const [ cbehomes, setCbehomes ] = useState([]);
  useEffect(() => {
    (
      async () => {
        const results = await fetch('/api/home');

        const resultsJson = await results.json();
   
        setCbehomes(resultsJson);
      }
    )();
  }, []);
  const css = { maxWidth: '100%', height: 'auto', margin: '0 auto', display: 'block' }
  return (
    <React.Fragment>
      
      <Head>
        <title>Colchester Breathe Easy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className="container-fluid"  id="ldin"  onLoad={showPage()}>
      <div className="bubble x1"></div>
        <div className="bubble x2"></div>
        <div className="bubble x3"></div>
        <div className="bubble x4"></div>
        <div className="bubble x5"></div>
        <div className="bubble x6"></div>
        <div className="bubble x7"></div>
        <div className="bubble x8"></div>
        <div className="bubble x9"></div>
        <div className="bubble x10"></div>
        <div className="outerNavBar">
          <div className="bubble x1"></div>
          <div className="bubble x2"></div>
          <div className="bubble x3"></div>
          <div className="bubble x4"></div>
          <div className="bubble x5"></div>
          <div className="bubble x6"></div>
          <div className="bubble x7"></div>
          <div className="bubble x8"></div>
          <div className="bubble x9"></div>
          <div className="bubble x10"></div>
        </div>
        <div className="row home-panel">
          <div className="col-lg-2 col-md-12"></div>
          <div className="col-lg-8 col-md-12">
            <div className="container-fluid">
              <div className="row">
                
                <LogoBanner />
              </div>

              <div className="row home-block">
                <div className="col-12">
                  
                  {cbehomes &&
                    cbehomes.map((m) => (
                      <React.Fragment
                        key={m._id}
                        
                      >
                        <div>
                          <div className="">
                            <h1>{parse(m.cbeHomeHead.replace(/(<([^>]+)>)/gi, ""))}</h1>
                            {parse(m.cbeHomeBody)}
                            <Image src={m.cbeHomeImage} alt="" width="908" height="679" style={css} layout="responsive" />
                          </div>

                          {/* {auth.getRole() && auth.getCurrentUser() && (
                            <React.Fragment>
                              <button className="btn btn-primary col-6 col-xs-12">
                                <Link
                                  className="edit-btn"
                                  to={`/home/${m._id}`}
                                >
                                  <i
                                    class="fa fa-pencil-square-o fa-2x"
                                    aria-hidden="true"
                                  ></i>
                                </Link>
                              </button>
                              <button
                                className="btn btn-primary col-6 col-xs-12"
                                onClick={() => this.handleDelete(m)}
                              >
                                <i className="fa fa-trash fa-2x"></i>
                              </button>
                            </React.Fragment>
                          )} */}
                        </div>
                      </React.Fragment>
                    ))}
                </div>
              </div>
            </div>
          </div>
          <div className="col-lg-2 col-md-12"></div>
        </div>
      </main>

      
      </React.Fragment>
  )
}
